In [1]:
print("hello")

hello


In [2]:
import numpy as np

In [14]:
#utwórz tablicę zawierającą 10 zer,


In [8]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
#utwórz tablicę zawierającą 10 piątek

In [15]:
np.repeat(5, 10)

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [ ]:
#utwórz tablicę zawierającą liczby od 10 do 50

In [13]:
np.arange(10,51,)


array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [16]:
#utwórz macierz (tablica wielowymiarowa) o wymiarach 3x3 zawierającą liczby od 0 do 8,

In [17]:
a = np.matrix('0 1 2; 3 4 5;6 7 8')

In [18]:
a


matrix([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [20]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [21]:
#utwórz macierz jednostkową o wymiarach 3x3,

In [22]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [24]:
#utwórz macierz o wymiarach 5x5 zawierającą liczby z dystrybucji normalnej

In [23]:
np.random.randn(5, 5) 

array([[ 1.17344671, -0.70953395, -0.31197995, -1.0288922 ,  1.65612155],
       [ 0.12133837, -0.96008242, -0.24338001,  0.16828415,  0.41011368],
       [ 0.4804889 , -0.55680677,  0.48053172,  0.18571519,  0.64270297],
       [-0.54950608,  0.45474798, -0.64620081,  0.28036794, -0.42724392],
       [-1.0015352 ,  0.69868758, -1.87269006,  0.40685194, -0.81698561]])

In [25]:
#utwórz macierz o wymiarach 10x10 zawierającą liczby od 0,01 do 1 z krokiem 0,01,

In [36]:
np.arange(0.01,1.01,0.01)

array([0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 , 0.11,
       0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 , 0.21, 0.22,
       0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 , 0.31, 0.32, 0.33,
       0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 , 0.41, 0.42, 0.43, 0.44,
       0.45, 0.46, 0.47, 0.48, 0.49, 0.5 , 0.51, 0.52, 0.53, 0.54, 0.55,
       0.56, 0.57, 0.58, 0.59, 0.6 , 0.61, 0.62, 0.63, 0.64, 0.65, 0.66,
       0.67, 0.68, 0.69, 0.7 , 0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77,
       0.78, 0.79, 0.8 , 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88,
       0.89, 0.9 , 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99,
       1.  ])

In [37]:
#utwórz tablicę zawierającą 20 liniowo rozłożonych liczb między 0 a 1 (włącznie z 0 i 1),

In [33]:
np.linspace(0, 1, num=20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [34]:
#utwórz tablicę zawierającą losowe liczby z przedziału (1, 25), następnie zamień ją na macierz o wymiarach 5 x 5 z tymi samymi liczbami:

In [41]:
x=np.random.randint(1,25, size=(5, 5))

In [42]:
x

array([[ 1, 20,  7, 14, 24],
       [ 1, 18,  5, 23,  9],
       [ 5, 22, 19, 18,  3],
       [ 8, 12,  9,  3, 22],
       [ 6, 13,  9, 24,  7]])

In [45]:
#oblicz sumę wszystkich liczb w ww. macierzy.

In [43]:
x.sum()

302

In [46]:
#oblicz średnią wszystkich liczb w ww. macierzy.

In [44]:
x.mean()

12.08

In [47]:
#oblicz standardową dewiację dla liczb w ww. macierzy.

In [48]:
x.std()

7.562645039931465

In [49]:
#oblicz sumę każdej kolumny ww. macierzy i zapisz ją do tablicy.

In [51]:
x.sum(axis=0)

array([21, 85, 49, 82, 65])

In [52]:
#utwórz macierz o wymiarach 5x5 zawierającą losowe liczby z przedziału (0, 100)

In [55]:
y=np.random.randint(100, size=(5, 5))

In [56]:
y

array([[ 0,  7, 21, 63, 73],
       [87,  8, 28, 29, 15],
       [ 2, 86, 81, 23, 41],
       [20, 74, 32,  7, 43],
       [63, 59, 11, 93, 25]])

In [58]:
#oblicz medianę tych liczb.

In [59]:
np.median(y)

29.0

In [60]:
#znajdź najmniejszą liczbę tej macierzy,

In [61]:
y.min()

0

In [62]:
#znajdź największą liczbę tej macierzy,

In [63]:
y.max()

93

In [65]:
#utwórz macierz o wymiarach różnych od siebie i większych od 1, zawierającą losowe liczby z przedziału (0, 100) i dokonaj jej transpozycji,

In [64]:
z=np.random.randint(100, size=(3, 5))

In [66]:
z

array([[29,  0, 26, 91, 70],
       [85, 61, 19, 11, 15],
       [93, 19, 32, 15, 98]])

In [67]:
z.transpose()

array([[29, 85, 93],
       [ 0, 61, 19],
       [26, 19, 32],
       [91, 11, 15],
       [70, 15, 98]])

In [68]:
#utwórz dwie macierze o odpowiednich wymiarach, większych od 2 i dodaj je do siebie.

In [70]:
x

array([[69, 25, 29, 69, 86],
       [63, 98, 72, 26, 77],
       [39, 93, 48, 46, 91],
       [42, 37, 63, 94, 76],
       [31, 69, 58, 27, 89]])

In [71]:
y

array([[ 0,  7, 21, 63, 73],
       [87,  8, 28, 29, 15],
       [ 2, 86, 81, 23, 41],
       [20, 74, 32,  7, 43],
       [63, 59, 11, 93, 25]])

In [69]:
np.add(x,y)

array([[ 69,  32,  50, 132, 159],
       [150, 106, 100,  55,  92],
       [ 41, 179, 129,  69, 132],
       [ 62, 111,  95, 101, 119],
       [ 94, 128,  69, 120, 114]])

In [74]:
#utwórz dwie macierze o odpowiednich wymiarach, większych od 2 i pomnóż je przez siebie

In [73]:
np.matmul(x, y)

array([[ 9031, 13357,  7652, 14220, 11718],
       [14041, 13884, 11578, 15810, 12064],
       [14840, 13918,  9784, 15043, 10463],
       [10013, 17448, 10865, 12894, 12146],
       [12266, 13006,  9124, 13754,  9062]])